### ISSUE TITLE
Move to AtomLinter org?

### ISSUE THREAD

**Issue by Arcanemagus** [wooorm/atom-linter-alex#13]
Would you want to migrate this repo to the AtomLinter organization? You would still have Owner rights on the repo, there would just be a few more people actively helping on the project :wink:

If you want to contact me or one of the other [organization owners](https://github.com/orgs/AtomLinter/people?query=role%3Aowner+) to get the process started. The current set of instructions / guidelines can be found [here](https://github.com/AtomLinter/Meta/wiki/Migrating-a-repository).

**Comment by wooorm** [comment]
@Arcanemagus Sorry for the late response. Thanks for the offer, but for now I’m doing fine on my own, maybe even better as I’m updating this linter at the same time as the main project.

I’ll keep it in mind though, maybe in the future!
