### ISSUE TITLE
Update Alex to Alex 2.0

### ISSUE THREAD

**Issue by rugk** [wooorm/atom-linter-alex#15]
[Alex 2.0.0](https://github.com/wooorm/alex/releases/tag/2.0.0) was just released including new support for profanities and more things.
It would be nice if this package can be updated.

**Comment by wooorm** [comment]
Thanks, done!

**Comment by rugk** [comment]
And just some hours after you updated it there is already the [2.2.1](https://github.com/wooorm/retext-equality/releases/tag/2.2.1) release.

**Comment by wooorm** [comment]
You can uninstall and re-install atom packages to include updated dependencies.

**Comment by rugk** [comment]
Just updating does not work?

**Comment by wooorm** [comment]
Yes, it will, but it’s “wrong”, in my opinion. The version of linter-alex describes the code of linter-alex and its stability, not the code of dependencies deep down. I haven’t updated alex either. That’s a good thing! If something deep down is fixed, I don’t update the version of alex, nor linter-alex.
