### ISSUE TITLE
Freezes atom

### ISSUE THREAD

**Issue by dflock** [wooorm/atom-linter-alex#16]
Installed `linter-alex` 2.0.0 and it froze atom as soon as I loaded a new document. Atom sits there frozen for a while before crashing. Restarting it just makes it crash again, presumably because that document is being loaded.

Disabling `linter-alex` with `apm` and restarting atom fixes the problem.

I had this happen yesterday, at home, on atom 1.5.4 - and again today at work, on atom 1.6.0, on a different machine. Different installs, different machines, different versions of atom, different documents loaded.

**Comment by wooorm** [comment]
Where all the documents quite big?

**Comment by dflock** [comment]
No, although I do have quite a lot of windows/tabs open at a time, so it might be that.

**Comment by wooorm** [comment]
Well, low performance with many / long documents is unfortunately expected. And not fixable.
