### ISSUE TITLE
Feature: `.alexrc` and `.alexignore` files

### ISSUE THREAD

**Issue by rugk** [wooorm/atom-linter-alex#17]
.alexrc:

``` json
{
  "allow": ["UK"]
}
```

When placing this file into the root dir, `UK` is still considered profane.

**Comment by wooorm** [comment]
@rugk Whoops, yes, `.alexrc` files aren’t supported in this module yet. Thanks for pointing it out!

**Comment by rugk** [comment]
And what about `.alexignore` files? Are they already used?

**Comment by wooorm** [comment]
See title :)

**Comment by rugk** [comment]
So this means no. :smiley:

**Comment by ChasNelson1990** [comment]
Hi,
Any joy implementing this?

**Comment by wooorm** [comment]
Finally fixed in bf14015!
