### ISSUE TITLE
Red dots displayed at previous line

### ISSUE THREAD

**Issue by rugk** [wooorm/atom-linter-alex#4]
If the bad word is on the new line it sometimes display the red dots a bit too early:
![alexlinter](https://cloud.githubusercontent.com/assets/11966684/9915484/a21ebfa2-5cb7-11e5-8884-f51c70583db3.PNG)

**Comment by wooorm** [comment]
Weird, I’m not getting it. What `linter` settings/version are you using?

![screen shot 2015-09-18 at 5 44 11 p m](https://cloud.githubusercontent.com/assets/944406/9963729/f1f18ea8-5e2c-11e5-9fc2-505133272ace.png)

**Comment by rugk** [comment]
Linter 1.5.3
![lintersettings](https://cloud.githubusercontent.com/assets/11966684/9968169/3b6d1614-5e47-11e5-9698-3f9e3a2edac4.PNG)

**Comment by wooorm** [comment]
1.5.3? I think [1.5.2](https://github.com/atom-community/linter/blob/5220b236a512e93c7d831da2725ab4b1e96e33ee/package.json#L5) is the latest?

Anyway, even with your settings I cannot seem to reproduce. Did you see it in other examples too?

**Comment by wooorm** [comment]
@steelbrain Any idea what this is about? I’m thinking it has more to do with linter than with alex/mdast/retext?

**Comment by steelbrain** [comment]
@wooorm Atom stores buffer lines in a 0-indexed manner, so if `linter-alex` tells you there's error on line 1, you must tell `linter` that there's an error on line 0.

**Comment by wooorm** [comment]
@steelbrain I think I’m already [accounting for that](https://github.com/wooorm/atom-linter-alex/blob/576810de3d8bde9b37ca44c7302d1261446c1160/index.js#L42-L48). Anyway, that doesn’t explain why @rugk sees something different from me, or am I missing something?

**Comment by steelbrain** [comment]
Well. The old school workaround work almost always in those cases.

```
mv ~/.atom ~/.atom-backup
apm install linter linter-alex
```

**Comment by wooorm** [comment]
Thanks, but I’m still getting the correct results:

![screen shot 2015-09-18 at 10 06 18 p m](https://cloud.githubusercontent.com/assets/944406/9969872/9662322a-5e51-11e5-8928-546844018780.png)

@rugk Could you try this too? Maybe the example of the text you gave me was too short,

**Comment by rugk** [comment]
> 1.5.3? I think 1.5.2 is the latest?

Yes of course. 1.5.2 - I was wrong.

The example was from [HTTPS-everywhere](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md) BTW.

It also does not matter how wide the window is:
![redotsissue](https://cloud.githubusercontent.com/assets/11966684/9971090/a139e9c4-5e59-11e5-9d7e-d556b594c0b3.PNG)

And BTW this error display for 'host' is also something where the red dots are at the wrong position:
![redotsissue2](https://cloud.githubusercontent.com/assets/11966684/9970996/2a33a252-5e59-11e5-909c-fa65816bdb55.PNG)

**Comment by wooorm** [comment]
@rugk Well, I didn’t find your line-ending case, but I did find a bug relating to entities (your second example). Maybe if I fix that one, the first one’s gone too.

Thanks for all the info!
