### ISSUE TITLE
Many nested paths

### ISSUE THREAD

**Issue by rugk** [wooorm/atom-linter-alex#6]
On the installation I e.g. have the following path: `linter-alex\node_modules\alex\node_modules\update-notifier\node_modules\latest-version\node_modules\package-json\node_modules\got\node_modules\duplexify\node_modules\end-of-stream\node_modules\once\node_modules\wrappy\test`
(that's only the part after the package dir)

On Windows 7 in certain circumstances this even gave me a message that the path is too long (and it was an NTFS file system), so please try too use paths which are a bit shorter and don't contain thousand empty subfolders named `node_modules`.

**Comment by wooorm** [comment]
This is out of my control; not something I am able to change. It’s good practice to depend on packages, and it’s a problem with npm’s design. Read this on how to “fix” it: http://engineroom.teamwork.com/dealing-with-long-paths/

**Comment by rugk** [comment]
Okay, nice link.

**Comment by wooorm** [comment]
:+1:
