### ISSUE TITLE
Don't use both `html` and `text` with linter

### ISSUE THREAD

**Issue by blakeembrey** [wooorm/atom-linter-alex#9]
You can only render one or the other. This is an error now too, so it'll be breaking when trying to render the errors.

Edit: I was going to do a PR, but wasn't sure which one you actually wanted to keep.

**Comment by wooorm** [comment]
Oh really? Is that new in atom/-linter (I didn't previously notice)!

If you're still up for a PR I'm all for keeping just the HTML version (it highlights some useful info), but I'm not sure if that has any negative consequences?!
